// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KGyhpN1nis7CR602pl82uX8zRGyv2uY',
    appId: '1:846453367990:android:9bc9173bce21c49a27b217',
    messagingSenderId: '846453367990',
    projectId: 'najlepszy-vet-wawa-22012023',
    storageBucket: 'najlepszy-vet-wawa-22012023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-DROp6x-Z0kxwwhZ5L8McrBlzy4JRxNg',
    appId: '1:846453367990:ios:d33e344659e6f03d27b217',
    messagingSenderId: '846453367990',
    projectId: 'najlepszy-vet-wawa-22012023',
    storageBucket: 'najlepszy-vet-wawa-22012023.appspot.com',
    iosClientId: '846453367990-e3m7f6snhqr64rmt2lefqh067lm7u66d.apps.googleusercontent.com',
    iosBundleId: 'com.aduzja.najlepszyVetWarszawa',
  );
}
